# Generated by Django 4.2.2 on 2024-04-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Shoulder Bags', max_length=100),
        ),
    ]
