# Generated by Django 4.2.2 on 2024-04-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='Leather Bags', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Shoulder Bag', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='title',
            field=models.CharField(default='Ahiba', max_length=100),
        ),
    ]
