# Generated by Django 4.2.2 on 2024-04-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_title_alter_product_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='date',
        ),
    ]
