# Generated by Django 4.2.2 on 2024-04-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_vendor_cover_image_remove_vendor_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
