# Generated by Django 4.2.2 on 2024-06-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_life_product_mfd_product_stock_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist_model',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
