# Generated by Django 4.2.2 on 2024-06-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_wishlist_model_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
