# Generated by Django 4.2.2 on 2024-06-30 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_wishlist_model_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist_model',
            name='session_key',
        ),
        migrations.AlterField(
            model_name='wishlist_model',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
        migrations.AlterField(
            model_name='wishlist_model',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
