# Generated by Django 4.2.2 on 2024-06-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_wishlist_model_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='life',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mfd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='warranty_period',
        ),
        migrations.AddField(
            model_name='product',
            name='Material',
            field=models.CharField(blank=True, default='Leather', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.CharField(blank=True, default='100', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='days_return',
            field=models.CharField(default='14', max_length=100),
        ),
    ]
