# Generated by Django 4.2.2 on 2024-06-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cartorder_billing_address_cartorder_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderproducts',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='cartorderproducts',
            name='shipping_address',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartorderproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartorderproducts',
            name='product_status',
            field=models.CharField(default='processing', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorderproducts',
            name='total',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=10),
        ),
    ]
