# Generated by Django 4.2.2 on 2024-07-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_cartorderproducts_billing_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist_model',
        ),
    ]
