# Generated by Django 4.2.2 on 2024-07-03 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_product_color_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Material',
        ),
    ]
